gamma = 5.0/3
fcfl = 0.99
z0 = 3.1
zf = 7.4
nint = 64
#nint = 128
timeEnd = 1.0
functiontype = 'sine'
#functiontype = 'defined'
verbose = False
schemeType = "lf"  # scheme type may be lf(Lax - Fr) of fg (first generation)
